<x-app-layout>
    <x-slot name="header">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between print:hidden">
            <div>
                <p class="text-sm uppercase tracking-[0.2em] text-red-200">Admin</p>
                <h1 class="section-title mt-2">Student Record</h1>
                <p class="section-copy mt-2">Review this account's listings, transaction records, receipts, payment proof status, and marketplace activity.</p>
            </div>
            <div class="flex flex-col gap-3 sm:flex-row">
                <a href="{{ route('admin.users') }}" class="btn-secondary">User List</a>
                <button onclick="window.print()" class="btn-primary">Print Record</button>
            </div>
        </div>
    </x-slot>

    <div class="page-wrap printable-report space-y-6 print:max-w-none print:text-slate-900">
        <div class="glass-card report-summary p-6 print:border print:border-slate-200 print:bg-white print:shadow-none">
            <div class="flex flex-col gap-4 border-b border-white/10 pb-5 sm:flex-row sm:items-start sm:justify-between print:border-slate-200">
                <div>
                    <p class="transaction-kicker print:text-red-700">UM-Pasa Student Record</p>
                    <h2 class="mt-2 text-3xl font-bold text-white print:text-slate-900">{{ $user->name }}</h2>
                    <div class="mt-3 grid gap-2 text-sm text-slate-300 sm:grid-cols-3 print:text-slate-700">
                        <p><strong>Email:</strong> {{ $user->email }}</p>
                        <p><strong>Role:</strong> {{ ucfirst($user->role) }}</p>
                        <p><strong>Joined:</strong> {{ $user->created_at->format('F d, Y') }}</p>
                        <p><strong>Generated date:</strong> {{ now()->format('F d, Y h:i A') }}</p>
                        <p><strong>Generated by:</strong> {{ auth()->user()->name }}</p>
                    </div>
                </div>
                <span class="badge-base border-white/15 bg-white/10 text-slate-200 print:border-slate-300 print:bg-slate-100 print:text-slate-700">
                    {{ ucfirst($user->role) }}
                </span>
            </div>

            <div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-7">
                <div class="transaction-meta-tile print:bg-slate-50"><span>Listings</span><strong>{{ $stats['listings'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Approved Listings</span><strong>{{ $stats['approvedListings'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Transactions</span><strong>{{ $stats['transactions'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Completed</span><strong>{{ $stats['completed'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Bought</span><strong>{{ $stats['bought'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Sold</span><strong>{{ $stats['sold'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Earned</span><strong>P{{ number_format($stats['earned'], 2) }}</strong></div>
            </div>
        </div>

        <div class="table-shell report-table print:border print:border-slate-200 print:bg-white print:shadow-none">
            <div class="report-section-title p-4 text-lg font-semibold text-white print:text-slate-900">Listing Records</div>
            <div class="overflow-x-auto">
                <table class="min-w-full">
                    <thead class="table-head">
                        <tr>
                            <th class="px-4 py-4">Item</th>
                            <th class="px-4 py-4">Type</th>
                            <th class="px-4 py-4">Status</th>
                            <th class="px-4 py-4">Review</th>
                            <th class="px-4 py-4">Price</th>
                            <th class="px-4 py-4 print:hidden">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($items as $item)
                            <tr class="table-row">
                                <td class="px-4 py-4">
                                    <div class="font-semibold text-white print:text-slate-900">{{ $item->title }}</div>
                                    <div class="mt-1 text-xs uppercase tracking-[0.16em] text-slate-400 print:text-slate-500">{{ $item->category ?: 'General' }} · {{ $item->course_code }}</div>
                                </td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ ucfirst($item->listing_type) }}</td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ ucfirst($item->status) }}</td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ $item->getModerationStatusLabel() }}</td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ $item->price ? 'P' . number_format($item->price, 2) : 'Flexible' }}</td>
                                <td class="px-4 py-4 print:hidden">
                                    <a href="{{ route('marketplace.show', $item) }}" class="btn-secondary">View Item</a>
                                </td>
                            </tr>
                        @empty
                            <tr><td colspan="6" class="px-4 py-8 text-center text-slate-300 print:text-slate-700">No listings found for this user.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="print:hidden">{{ $items->links() }}</div>

        <div class="table-shell report-table print:border print:border-slate-200 print:bg-white print:shadow-none">
            <div class="report-section-title p-4 text-lg font-semibold text-white print:text-slate-900">Transaction Records</div>
            <div class="overflow-x-auto">
                <table class="min-w-full">
                    <thead class="table-head">
                        <tr>
                            <th class="px-4 py-4">ID</th>
                            <th class="px-4 py-4">Item</th>
                            <th class="px-4 py-4">Role</th>
                            <th class="px-4 py-4">Other Party</th>
                            <th class="px-4 py-4">Status</th>
                            <th class="px-4 py-4">Payment</th>
                            <th class="px-4 py-4">Proof</th>
                            <th class="px-4 py-4">Tracking</th>
                            <th class="px-4 py-4 print:hidden">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($transactions as $transaction)
                            @php
                                $isSeller = $transaction->seller_id === $user->id;
                                $otherParty = $isSeller ? $transaction->buyer : $transaction->seller;
                            @endphp
                            <tr class="table-row">
                                <td class="px-4 py-4">#{{ $transaction->id }}</td>
                                <td class="px-4 py-4">{{ $transaction->item->title }}</td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ $isSeller ? 'Seller' : 'Buyer' }}</td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">
                                    <a href="{{ route('admin.users.record', $otherParty) }}" class="text-red-100 underline decoration-red-300/40 underline-offset-4 print:text-slate-900">
                                        {{ $otherParty->name }}
                                    </a>
                                </td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ ucfirst($transaction->status) }}</td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ $transaction->getPaymentMethodLabel() }}</td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ $transaction->getPaymentProofStatusLabel() }}</td>
                                <td class="px-4 py-4 text-slate-300 print:text-slate-700">{{ $transaction->getTrackingStatusLabel() }}</td>
                                <td class="px-4 py-4 print:hidden">
                                    <div class="flex flex-wrap gap-2">
                                        <a href="{{ route('transactions.show', $transaction) }}" class="btn-secondary">View Receipt</a>
                                        @if($transaction->payment_proof)
                                            <a href="{{ route('transactions.paymentProof.show', $transaction) }}" class="btn-secondary" target="_blank">View Uploaded Proof</a>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                        @empty
                            <tr><td colspan="9" class="px-4 py-8 text-center text-slate-300 print:text-slate-700">No transactions found for this user.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="print:hidden">{{ $transactions->links() }}</div>
    </div>
</x-app-layout>
