<x-app-layout>
    @php
        $filterSummary = collect([
            'Status' => $filters['status'] ?? 'All statuses',
            'Type' => match($filters['type'] ?? null) {
                'sell' => 'Sales',
                'rent' => 'Rentals',
                default => 'Sales and rentals',
            },
            'Category' => $filters['category'] ?? 'All categories',
            'Sort' => str($filters['sort'] ?? 'newest')->replace('_', ' ')->title(),
            'Rows' => (string) ($filters['per_page'] ?? 5),
        ]);
    @endphp

    <x-slot name="header">
        <div class="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between print:hidden">
            <div>
                <p class="text-sm uppercase tracking-[0.2em] text-red-200">Reports</p>
                <h1 class="section-title mt-2">Student Report</h1>
                <p class="section-copy mt-2">Printable summary of your listings, requests, rental durations, payment modes, and completed deals.</p>
            </div>
            <div class="flex flex-col gap-3 sm:flex-row">
                <a href="{{ route('dashboard') }}" class="btn-secondary">Dashboard</a>
                <button onclick="window.print()" class="btn-primary">Print Report</button>
            </div>
        </div>
    </x-slot>

    <div class="page-wrap printable-report space-y-6 print:max-w-none print:text-slate-900">
        <div class="glass-card report-summary p-6 print:border print:border-slate-200 print:bg-white print:shadow-none">
            <div class="flex flex-col gap-4 border-b border-white/10 pb-5 sm:flex-row sm:items-start sm:justify-between print:border-slate-200">
                <div>
                    <p class="transaction-kicker print:text-red-700">UM-Pasa Student Report</p>
                    <h2 class="mt-2 text-3xl font-bold text-white print:text-slate-900">{{ $user->name }}</h2>
                    <div class="mt-3 grid gap-2 text-sm text-slate-300 sm:grid-cols-3 print:text-slate-700">
                        <p><strong>Generated date:</strong> {{ now()->format('F d, Y h:i A') }}</p>
                        <p><strong>Generated by:</strong> {{ auth()->user()->name }}</p>
                        <p><strong>Pagination:</strong> Listings page {{ $items->currentPage() }} of {{ $items->lastPage() }}, Transactions page {{ $transactions->currentPage() }} of {{ $transactions->lastPage() }}</p>
                    </div>
                    <div class="mt-4 report-filter-summary">
                        @foreach($filterSummary as $label => $value)
                            <span><strong>{{ $label }}:</strong> {{ $value }}</span>
                        @endforeach
                    </div>
                </div>
                <div class="text-sm text-slate-300 print:text-slate-600">{{ $user->email }}</div>
            </div>

            <div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
                <div class="transaction-meta-tile print:bg-slate-50"><span>Listings</span><strong>{{ $stats['listed'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Approved Listings</span><strong>{{ $stats['approvedListings'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Transactions</span><strong>{{ $stats['transactions'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Completed Deals</span><strong>{{ $stats['completed'] }}</strong></div>
                <div class="transaction-meta-tile print:bg-slate-50"><span>Earned</span><strong>P{{ number_format($stats['earned'], 2) }}</strong></div>
            </div>
        </div>

        <form method="GET" class="glass-card grid gap-4 p-5 md:grid-cols-5 print:hidden">
            <div>
                <label class="text-sm font-medium text-slate-200">Transaction Status</label>
                <select name="status" class="glass-input">
                    <option value="">All statuses</option>
                    @foreach(['pending', 'approved', 'rejected', 'completed'] as $status)
                        <option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ ucfirst($status) }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label class="text-sm font-medium text-slate-200">Type</label>
                <select name="type" class="glass-input">
                    <option value="">Sales and rentals</option>
                    <option value="sell" @selected(($filters['type'] ?? '') === 'sell')>Sales</option>
                    <option value="rent" @selected(($filters['type'] ?? '') === 'rent')>Rentals</option>
                </select>
            </div>
            <div>
                <label class="text-sm font-medium text-slate-200">Category</label>
                <select name="category" class="glass-input">
                    <option value="">All categories</option>
                    @foreach($categories as $category)
                        <option value="{{ $category }}" @selected(($filters['category'] ?? '') === $category)>{{ $category }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label class="text-sm font-medium text-slate-200">Sort</label>
                <select name="sort" class="glass-input">
                    <option value="newest" @selected(($filters['sort'] ?? 'newest') === 'newest')>Newest</option>
                    <option value="oldest" @selected(($filters['sort'] ?? '') === 'oldest')>Oldest</option>
                    <option value="title" @selected(($filters['sort'] ?? '') === 'title')>Title</option>
                    <option value="status" @selected(($filters['sort'] ?? '') === 'status')>Status</option>
                </select>
            </div>
            <div>
                <label class="text-sm font-medium text-slate-200">Rows</label>
                <select name="per_page" class="glass-input">
                    <option value="5" @selected((int)($filters['per_page'] ?? 5) === 5)>5</option>
                    <option value="10" @selected((int)($filters['per_page'] ?? 5) === 10)>10</option>
                    <option value="20" @selected((int)($filters['per_page'] ?? 5) === 20)>20</option>
                </select>
            </div>
            <div class="flex items-end gap-3 md:col-span-5">
                <button class="btn-primary" type="submit">Apply Filters</button>
                <a href="{{ route('reports.student') }}" class="btn-secondary">Reset</a>
            </div>
        </form>

        <div class="table-shell report-table print:border print:border-slate-200 print:bg-white print:shadow-none">
            <div class="report-section-title p-4 text-lg font-semibold text-white print:text-slate-900">Listings</div>
            <div class="overflow-x-auto">
                <table class="min-w-full">
                    <thead class="table-head">
                        <tr>
                            <th class="px-4 py-4">Item</th>
                            <th class="px-4 py-4">Type</th>
                            <th class="px-4 py-4">Rental / Sale Status</th>
                            <th class="px-4 py-4">Review</th>
                            <th class="px-4 py-4">Payments</th>
                            <th class="px-4 py-4">Price</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($items as $item)
                            <tr class="table-row">
                                <td class="px-4 py-4">{{ $item->title }}</td>
                                <td class="px-4 py-4 text-slate-300">{{ ucfirst($item->listing_type) }}</td>
                                <td class="px-4 py-4 text-slate-300">{{ $item->listing_type === 'rent' ? (($item->minimum_rental_days ?? 1) . '-' . ($item->maximum_rental_days ?? $item->rental_duration_days ?? 'TBD') . ' day(s)') : ucfirst($item->status) }}</td>
                                <td class="px-4 py-4 text-slate-300">{{ $item->getModerationStatusLabel() }}</td>
                                <td class="px-4 py-4 text-slate-300">{{ implode(', ', $item->getAcceptedPaymentMethodLabels()) }}</td>
                                <td class="px-4 py-4 text-slate-300">{{ $item->price ? 'P' . number_format($item->price, 2) : 'Flexible' }}</td>
                            </tr>
                        @empty
                            <tr><td colspan="6" class="px-4 py-8 text-center text-slate-300">No listings yet.</td></tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="print:hidden">{{ $items->links() }}</div>

        <div class="table-shell report-table print:border print:border-slate-200 print:bg-white print:shadow-none">
            <div class="report-section-title p-4 text-lg font-semibold text-white print:text-slate-900">Transactions</div>
            <div class="overflow-x-auto">
                <table class="min-w-full">
                    <thead class="table-head">
                        <tr>
                            <th class="px-4 py-4">ID</th>
                            <th class="px-4 py-4">Item</th>
                            <th class="px-4 py-4">Role</th>
                            <th class="px-4 py-4">Status</th>
                            <th class="px-4 py-4">Payment</th>
	                            <th class="px-4 py-4">Proof</th>
	                            <th class="px-4 py-4">Tracking</th>
	                            <th class="px-4 py-4">Date</th>
	                            <th class="px-4 py-4 print:hidden">Receipt</th>
	                        </tr>
                    </thead>
                    <tbody>
                        @forelse($transactions as $transaction)
                            <tr class="table-row">
                                <td class="px-4 py-4">#{{ $transaction->id }}</td>
                                <td class="px-4 py-4">{{ $transaction->item->title }}</td>
                                <td class="px-4 py-4 text-slate-300">{{ $transaction->seller_id === $user->id ? 'Seller' : 'Buyer' }}</td>
                                <td class="px-4 py-4 text-slate-300">{{ ucfirst($transaction->status) }}</td>
                                <td class="px-4 py-4 text-slate-300">{{ $transaction->getPaymentMethodLabel() }}</td>
	                                <td class="px-4 py-4 text-slate-300">{{ $transaction->getPaymentProofStatusLabel() }}</td>
	                                <td class="px-4 py-4 text-slate-300">{{ $transaction->getTrackingStatusLabel() }}</td>
	                                <td class="px-4 py-4 text-slate-300">{{ $transaction->created_at->format('M d, Y') }}</td>
	                                <td class="px-4 py-4 print:hidden">
	                                    <a href="{{ route('transactions.show', $transaction) }}" class="btn-secondary">View Receipt</a>
	                                </td>
	                            </tr>
	                        @empty
	                            <tr><td colspan="9" class="px-4 py-8 text-center text-slate-300">No transactions yet.</td></tr>
	                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        <div class="print:hidden">{{ $transactions->links() }}</div>
    </div>
</x-app-layout>
